### ISSUE TITLE
Changes to the templates for website generation

### ISSUE THREAD

**Issue by levinli303** [celestiamobile/celestia.mobi#24]
I'll keep a record of changes to the template of website here (since I don't intend to open source the code for website generation of celestia.mobi). Please also suggest changes here.

**Comment by levinli303** [comment]
Added support for short links.

https://celestia.mobi/news
https://celestia.mobi/tutorials
https://celestia.mobi/tools
have replaced the original links for tabs on https://celestia.mobi

https://celestia.mobi/addons is for add-ons however not used in tabs

https://celestia.mobi/privacy.html and https://celestia.mobi/privacy-zh-CN.html have been moved https://celestia.mobi/privacy

**Comment by DaveBowman2001** [comment]
Placing a **Last Update** date below the **Release Date** would help us keep track which version of a specific addon is currently uploaded on the mobi

**Comment by DaveBowman2001** [comment]
Seems like we have to link the Spacecraft Tutorial on spacecraft addons that aren't visible on the Present Day, as more and more comments are piling up regarding this issue on some addons

**Replacement:** This spacecraft/s may or may not appear on the Present Day. Read this Tutorial **[here](https://celestia.mobi/resources/guide?guide=6E1BB6B2-178D-F3DF-0C25-E7DE6741CBB5)** to know more
**Add-ons:**
```
084077EC-A1C7-76E2-D53B-86A99CDE2FD3
0DA83E71-74D6-00EB-BA85-090FFD45AA2F
0F2427F6-5205-7625-6937-1EB37A21FE26
1BE2453B-69DB-06F7-B2EB-1A3F3E54AB7B
1C6EC631-CE4B-6515-FC7A-A5171491600C
1D93EA6F-8FC4-A477-7660-B6B343BB8E61
26F27BB3-E99D-43FA-B654-854B082623ED
2787294E-0D4B-C42E-6039-720474FEF752
2882017D-E666-93AF-BA49-17E33B4F9B71
2A4A124B-B53C-50BF-DC6B-EE4869CC5C7D
2C93C6C4-AA21-D960-E907-41844D7C0128
3049F139-7245-3E2E-EDC3-6EAA1E8D303D
35DD15C3-F872-8561-4302-45B7FD337221
36BD3DBF-077A-26C9-2400-AFBB2054AC5A
37C41F40-9E2E-5715-4A1E-64BA75B49688
3800A29B-9CC8-BDA6-2A62-5DD27A967755
3B72676B-7D83-3860-D27E-26D2BE8C0FDA
43DA00E2-9B4A-E7ED-0CA1-1E2B2E41245A
465867E5-59B4-2E54-E36C-F64D7FF6A64C
47AC2544-C95D-5B70-EE88-F4E319B0C83D
4B9BC65A-312F-080D-8B27-4C78FB3E72CF
59AF2D3E-62EF-FDDB-A0F7-6980B7DCE265
63145F5B-02CC-4FAE-BBE3-D8F86FD7134D
64FA45B2-F62D-576D-6C74-23ED33C9F6C1
6DB7113E-1329-5425-0824-C286B9EB43C9
6E4A232D-D754-C4FA-39D7-ACD877D6E3D8
74332C90-95BD-4A30-AAAA-FC393F1F4F82
755519F3-5213-F6BD-A583-FE5C4F67AF56
77DCDAB9-5C56-208C-ADAC-56F51AD6512F
78E48D2D-39D3-4758-A97A-91783283C781
79FFB1A2-4DB3-7783-F863-0CB807D52AFB
7C588BE3-306E-4D6B-AB12-E3F9B04F6ECA
814612E8-40D4-B511-3BC2-AF10DB21D0D7
819812AB-3DAE-3484-9B91-A5363B33E15D
84499752-632A-4432-BB8A-19409056EC5B
89DBC264-A141-3C3E-F1EF-F6F266B2C4F2
8D21F53F-6A85-D0DD-E252-261CD429D107
8E2CC9A9-8C1E-2FFA-A181-EE57702D5D9A
90974046-2589-474F-856B-D5297605BD99
96EB2758-A62A-B7B1-B864-FE3C4AC82EB2
9BFB71A2-F44C-0696-C4E2-BA4E284194E6
9D1CDFBD-A9B7-68BB-855F-6C5B46F63D03
A1ED86A7-78B3-89B4-E967-ADB4581A3AD7
A1FD9F75-2E2D-A4B1-240E-A6D8E6353A2B
A2437ED3-5A19-425F-B95F-BE251D9ECD97
A2BBB352-E310-C92D-F99D-18F4727D7646
A79B502E-E959-86EE-4155-1D881B841006
AB5659E6-B8E8-FF5D-709F-E5BF251A4D3D
AD344048-CFEC-4AB1-A61E-3A6A2B9DE1BC
B99BC6E7-A035-6BA2-CA65-B7F9DA2BEDD1
BD70C15A-4AF3-C846-7A2D-E73B24E17575
C7E61327-98D1-E0E7-8C7D-7E11D82EE954
CF26C726-DD6F-1B43-AD60-98CF7ED0A8FD
D5688712-E454-3A5C-9E10-494EEBCACE72
DA2EBC67-CF3D-D960-BF63-78D831821DB3
E2BBC744-C70A-85D0-C3EF-DFD7D2AA4E35
EF2551AE-DAE4-A3CA-8677-D9E978EDB06E
F5C7FE4B-21D4-3ABB-7304-3ABDE7239BEE
F6E31C15-D5A5-D203-F272-9688AFE4C300
FF47F01E-3583-92F1-3C14-C152D503DC9C
```

**Comment by levinli303** [comment]
> Seems like we have to link the Spacecraft Tutorial on spacecraft addons that aren't visible on the Present Day, as more and more comments are piling up regarding this issue on some addons
> 
> **Replacement:** This spacecraft/s may or may not appear on the Present Day. Read this Tutorial **[here](https://celestia.mobi/resources/guide?guide=6E1BB6B2-178D-F3DF-0C25-E7DE6741CBB5)** to know more **Add-ons:**
> 
> ```
> 084077EC-A1C7-76E2-D53B-86A99CDE2FD3
> 0DA83E71-74D6-00EB-BA85-090FFD45AA2F
> 0F2427F6-5205-7625-6937-1EB37A21FE26
> 1BE2453B-69DB-06F7-B2EB-1A3F3E54AB7B
> 1C6EC631-CE4B-6515-FC7A-A5171491600C
> 1D93EA6F-8FC4-A477-7660-B6B343BB8E61
> 26F27BB3-E99D-43FA-B654-854B082623ED
> 2787294E-0D4B-C42E-6039-720474FEF752
> 2882017D-E666-93AF-BA49-17E33B4F9B71
> 2A4A124B-B53C-50BF-DC6B-EE4869CC5C7D
> 2C93C6C4-AA21-D960-E907-41844D7C0128
> 3049F139-7245-3E2E-EDC3-6EAA1E8D303D
> 35DD15C3-F872-8561-4302-45B7FD337221
> 36BD3DBF-077A-26C9-2400-AFBB2054AC5A
> 37C41F40-9E2E-5715-4A1E-64BA75B49688
> 3800A29B-9CC8-BDA6-2A62-5DD27A967755
> 3B72676B-7D83-3860-D27E-26D2BE8C0FDA
> 43DA00E2-9B4A-E7ED-0CA1-1E2B2E41245A
> 465867E5-59B4-2E54-E36C-F64D7FF6A64C
> 47AC2544-C95D-5B70-EE88-F4E319B0C83D
> 4B9BC65A-312F-080D-8B27-4C78FB3E72CF
> 59AF2D3E-62EF-FDDB-A0F7-6980B7DCE265
> 63145F5B-02CC-4FAE-BBE3-D8F86FD7134D
> 64FA45B2-F62D-576D-6C74-23ED33C9F6C1
> 6DB7113E-1329-5425-0824-C286B9EB43C9
> 6E4A232D-D754-C4FA-39D7-ACD877D6E3D8
> 74332C90-95BD-4A30-AAAA-FC393F1F4F82
> 755519F3-5213-F6BD-A583-FE5C4F67AF56
> 77DCDAB9-5C56-208C-ADAC-56F51AD6512F
> 78E48D2D-39D3-4758-A97A-91783283C781
> 79FFB1A2-4DB3-7783-F863-0CB807D52AFB
> 7C588BE3-306E-4D6B-AB12-E3F9B04F6ECA
> 814612E8-40D4-B511-3BC2-AF10DB21D0D7
> 819812AB-3DAE-3484-9B91-A5363B33E15D
> 84499752-632A-4432-BB8A-19409056EC5B
> 89DBC264-A141-3C3E-F1EF-F6F266B2C4F2
> 8D21F53F-6A85-D0DD-E252-261CD429D107
> 8E2CC9A9-8C1E-2FFA-A181-EE57702D5D9A
> 90974046-2589-474F-856B-D5297605BD99
> 96EB2758-A62A-B7B1-B864-FE3C4AC82EB2
> 9BFB71A2-F44C-0696-C4E2-BA4E284194E6
> 9D1CDFBD-A9B7-68BB-855F-6C5B46F63D03
> A1ED86A7-78B3-89B4-E967-ADB4581A3AD7
> A1FD9F75-2E2D-A4B1-240E-A6D8E6353A2B
> A2437ED3-5A19-425F-B95F-BE251D9ECD97
> A2BBB352-E310-C92D-F99D-18F4727D7646
> A79B502E-E959-86EE-4155-1D881B841006
> AB5659E6-B8E8-FF5D-709F-E5BF251A4D3D
> AD344048-CFEC-4AB1-A61E-3A6A2B9DE1BC
> B99BC6E7-A035-6BA2-CA65-B7F9DA2BEDD1
> BD70C15A-4AF3-C846-7A2D-E73B24E17575
> C7E61327-98D1-E0E7-8C7D-7E11D82EE954
> CF26C726-DD6F-1B43-AD60-98CF7ED0A8FD
> D5688712-E454-3A5C-9E10-494EEBCACE72
> DA2EBC67-CF3D-D960-BF63-78D831821DB3
> E2BBC744-C70A-85D0-C3EF-DFD7D2AA4E35
> EF2551AE-DAE4-A3CA-8677-D9E978EDB06E
> F5C7FE4B-21D4-3ABB-7304-3ABDE7239BEE
> F6E31C15-D5A5-D203-F272-9688AFE4C300
> FF47F01E-3583-92F1-3C14-C152D503DC9C
> ```

I still haven't got around adding this, but this will be a difficult list to maintain so I'd rather not. Instead I still think we should do https://github.com/levinli303/celestia.mobi/issues/24#issuecomment-1169911919 instead

**Comment by levinli303** [comment]
some new short links:

https://celestia.mobi/web
https://celestia.mobi/help/welcome
https://celestia.mobi/help/dependencies
https://celestia.mobi/help/flight-mode
https://celestia.mobi/help/game-controller
https://celestia.mobi/help/xbox

**Comment by levinli303** [comment]
Added shortlinks to prepare for GitHub based comment system.

https://celestia.mobi/addon -> https://celestia.mobi/resources/item
https://celestia.mobi/article -> https://celestia.mobi/resources/guide

**Comment by levinli303** [comment]
Added shortlink and added support for custom download file name in page

https://celestia.mobi/download

**Comment by levinli303** [comment]
Redirect /privacy.html to /privacy
Added https://celestia.mobi/help/development which redirects to https://github.com/levinli303/Celestia/wiki/Development

**Comment by levinli303** [comment]
Redirect /feedback to https://github.com/celestiamobile/celestia.mobi/issues
