### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by levinli303** [celestiamobile/celestia.mobi#57]
The current website is largely based on https://testflight.apple.com/ especially the css stylesheet.

Need to migrate to other implementations like Tailwind CSS https://tailwindcss.com

**Comment by 13940951572** [comment]
你好！我问一下你们插件有个电影太空旅客里宇宙飞船怎么能运行？
![Uploading Screenshot_20230816_102306_Celestia.png…]()

**Comment by TheLostProbe** [comment]
in terms of the actual design of the site, i think it's ok and works very well on phone screens (which is what it's supposed to do), so i think just iterate on this design a little bit.
i'm no expert but tailwind css looks very useful so it probably wouldn't hurt to switch over to that

**Comment by levinli303** [comment]
it is not a priority for now, let me close this.
