### ISSUE TITLE
Bug reporting

### ISSUE THREAD

**Issue by levinli303** [celestiamobile/celestia.mobi#62]
Most users will not make post issues on GitHub when they find a bug. The mobile bugs reports I have received are mostly by emails. It is also hard to get information from the users to diagnose the bug because of communication.

I plan to add a “Report a Bug” button in app, which gathers the necessary information for bug diagnosis and send via email (opens the default email client). It will include:
1. App version/build
2. Installed add-ons (only the celestia.mobi ones)
3. OpenGL info
4. Current CEL url

**Comment by DaveBowman2001** [comment]
Sounds good. Usually addon bugs are sometimes directly mentioned in the comments section, but most of it are just random bs...hopefully that would filter it out through the `Report a Bug` feature

**Comment by levinli303** [comment]
i've implemented an example here. For iOS/macOS, it will be in-app email composing. Android/Windows will go to default email client with similar expeirience.

https://github.com/celestiamobile/celestia.mobi/assets/17924287/61752172-db4d-4bea-b03e-4d0d943abd30

**Comment by levinli303** [comment]
1.5.24 has been released with this feature.
