### ISSUE TITLE
Stars Visual Bug while Galaxies are On

### ISSUE THREAD

**Issue by DaveBowman2001** [celestiamobile/celestia.mobi#63]
As per @SpaceExplorer on Discord...
> Bug in mobi: When moving away from a star at a certain distance, its brightness is failed. Occurs only when `Galaxies` is on.

![20230727_105623](https://github.com/celestiamobile/celestia.mobi/assets/95486841/4a7dcd19-b02a-4a8c-8eeb-1daed8bddb84)
![20230727_105638](https://github.com/celestiamobile/celestia.mobi/assets/95486841/13a0534b-236a-4c75-b82b-5252793b7727)

**Comment by levinli303** [comment]
1.5.24 has been released
