### ISSUE TITLE
Pseudo categories

### ISSUE THREAD

**Issue by levinli303** [celestiamobile/celestia.mobi#65]
Just like https://celestia.mobi/resources/popular which shows the top visits in the last week, it is not an actual category but we can show it as a category in https://celestia.mobi/resources/categories (thus available on mobile too)

we can possibly do
1. top visits
2. new add-ons
3. recently updated add-ons

**Comment by DaveBowman2001** [comment]
Oh right, I totally forgot that the `Most Popular` category is a thing for a long time now lol. 

One question though, how will the `Recently updated` category will function? Will they follow the indicated `Last Updated` date on their pages, or the order they were submitted as PRs in the [Addon Validator](https://github.com/celestiamobile/celestia-addon-validator/pulls)?

**Comment by levinli303** [comment]
For new add-ons, i want to use the internal creation date for add-ons, to determine what is new (based on when it is uploaded) instead of release date.

For recently updated, i want to use "Last Updated" field because the internal modification date (based on when it is uploaded) will be the same as creation date if there is not an update. so with internal modification date, it will also include new add-ons which is something i want to avoid.

**Comment by levinli303** [comment]
i might be putting this behind a paywall if i implement in-app purchase, since this is a nice-to-have, non-critical feature.

**Comment by levinli303** [comment]
Most Visits: https://celestia.mobi/resources/popular
Recently Updated: https://celestia.mobi/resources/updated
Recently Published: https://celestia.mobi/resources/published

@DaveBowman2001  we would need cover images for the three categories

<img width="993" alt="Screenshot 2023-08-21 at 19 29 38" src="https://github.com/celestiamobile/celestia.mobi/assets/17924287/d940d092-6cbc-44ea-b0e5-c6a525a08552">

Although it will be a paid feature, these links will remain valid for any user.

**Comment by DaveBowman2001** [comment]
Will do

**Comment by DaveBowman2001** [comment]
Sorry for the very long delay. Here are the cover images for the following pseudo-categories:
## Most Viewed
![Untitled](https://user-images.githubusercontent.com/95486841/225894502-e09fc81a-82a7-45cd-b41f-1493bba4fe56.jpg)
## Recently Updated
![cover_image](https://github.com/celestiamobile/celestia.mobi/assets/95486841/f163456a-7c5e-4d23-8593-e4ca3b4798bc)
## Recently Published
![cover_image](https://github.com/celestiamobile/celestia.mobi/assets/95486841/a7d6fdcb-a691-4b06-bc25-a2a141f88ae2)

**Comment by levinli303** [comment]
Looks great! thanks
<img width="918" alt="Screenshot 2023-08-31 at 21 47 26" src="https://github.com/celestiamobile/celestia.mobi/assets/17924287/418c2160-78ac-4042-955b-bf5f3de94d26">
