### ISSUE TITLE
In-app purchase

### ISSUE THREAD

**Issue by levinli303** [celestiamobile/celestia.mobi#68]
A potential solution to https://github.com/celestiamobile/celestia.mobi/issues/39

Premium features include (an ongoing list):
1. Access to pseudo categories in https://github.com/celestiamobile/celestia.mobi/issues/65
2. Quicker response from feedback, bug report (i have received quite a few reports since i added the in-app flow)

Some features that i'm considering...
1. Custom app icon (iOS)
2. Custom font

**Comment by Anthony-B-Russo10** [comment]
The best features for adding as payed ones would be anything that is non-essential (like the custom font you mentioned).

**Comment by levinli303** [comment]
Custom font is implemented in latest 1.6.0 beta.
