### ISSUE TITLE
change Discord link

### ISSUE THREAD

**Issue by TheLostProbe** [celestiamobile/celestia.mobi#70]
the Discord server invite in https://celestia.mobi/about should be changed to https://discord.com/invite/WEWDcJh because it is the never-ending invite (meaning it will never be invalid)

**Comment by levinli303** [comment]
I've made the change, the change should propagate in a few hours.

The content of about is at https://github.com/celestiamobile/celestia-mobi-content-localization/blob/main/guide-content/31C6B46F-825D-AF39-CEE8-B6F20811A615/en/data.html

**Comment by TheLostProbe** [comment]
I can see the new link now
