### ISSUE TITLE
Herschel and Luna 25 descriptions have issues

### ISSUE THREAD

**Issue by TheLostProbe** [celestiamobile/celestia.mobi#71]
@DaveBowman2001
https://media.discordapp.net/attachments/707026152937750578/1147427490755788800/Screen_Recording_20230901_223611_Celestia.mp4
https://media.discordapp.net/attachments/707026152937750578/1147427535525777470/Screen_Recording_20230901_223913_Celestia.mp4

**Comment by DaveBowman2001** [comment]
Obviously I've uploaded that Luna 25 addon way back in December 2022...however no time to update it now unfortunately

**Comment by DaveBowman2001** [comment]
Description for **Herschel** now fixed by https://github.com/celestiamobile/celestia-addon-validator/pull/983

**Comment by DaveBowman2001** [comment]
Description for **Luna 25** now fixed by https://github.com/celestiamobile/celestia-addon-validator/pull/984

**Comment by DaveBowman2001** [comment]
Issue should be closed by now
