### ISSUE TITLE
Source of "Celestia for Web"

### ISSUE THREAD

**Issue by chaojian-zhang** [celestiamobile/celestia.mobi#86]
Hi all, awesome work: https://celestia.mobi/resources/guide?guide=FFB76B69-1ADA-8F27-AD06-B0880F7EF43C

I have concerns regarding where is the source for this? I would really like to host something like that myself.

Thanks!

**Comment by levinli303** [comment]
Hi, it is based on SDL frontend of Celestia. When I have time I'll make the build steps and patches made to celestia available.

**Comment by chaojian-zhang** [comment]
> Hi, it is based on SDL frontend of Celestia. When I have time I'll make the build steps and patches made to celestia available.

Thanks for the reply, looking forward to it!

**Comment by levinli303** [comment]
@chaojian-zhang I've created a repo https://github.com/celestiamobile/celestia-web containing patches and build scripts I used to build Celestia for Web.

You can download the pre-built artifacts here: https://dev.azure.com/CelestiaProject/Celestia/_build?definitionId=12

**Comment by chaojian-zhang** [comment]
@levinli303 Thanks! Appreciated!
Very interesting setup, will investigate and let you know if anything comes up.

**Comment by chaojian-zhang** [comment]
@levinli303 I am seeing this from the Azure link:

<img width="382" height="192" alt="Image" src="https://github.com/user-attachments/assets/95b29a23-7809-4266-9fb8-f8c52e25adc9" />

Is there any other way you can make a latest build available?😂

**Comment by levinli303** [comment]
@chaojian-zhang  do not login with any account in Azure DevOps.

The build script is written for macOS specifically, you need macOS + Xcode to follow along.

**Comment by levinli303** [comment]
read into this https://github.com/celestiamobile/celestia-web/blob/main/jobs/build.yml in the process, a CelestiaResources folder will be created, replace withe the custom data you want.

the mobile fork is the same as the official repo except that the mobile has support for cockpit.
