### ISSUE TITLE
All spacecraft no longer able to reach Planets

### ISSUE THREAD

**Issue by DaveBowman2001** [celestiamobile/celestia.mobi#87]
Tested with [Psyche](https://celestia.mobi/resources/item?item=CD53DB88-EF1C-4E0E-929D-1C3A39A39DDD), [Voyager 1 and 2](https://celestia.mobi/resources/item?item=7EC33280-6523-8F01-FB57-AB000C1000DB), [Pioneer 10 and 11](https://celestia.mobi/resources/item?item=C276F25A-DFE6-7F33-10D1-135C7DA4AB72), [MRO](https://celestia.mobi/resources/item?item=4F9E7587-2CF9-B8EF-6089-381A88D653A2), etc....it seems that on the new updates, all spacecraft addons are now unable to reach their target objects when those said bodies are using their default orbits

**Comment by levinli303** [comment]
this should be a CelestiaProject/Celestia issue. would be better to post there.

**Comment by levinli303** [comment]
Fixed in 1.6.8, and released
